# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transform_img_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 301, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.image_label_2.setText("")
        self.image_label_2.setObjectName("image_label_2")
        self.horizontalLayout.addWidget(self.image_label_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(500, 40, 301, 451))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.image_label_3.setText("")
        self.image_label_3.setObjectName("image_label_3")
        self.horizontalLayout_2.addWidget(self.image_label_3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 180, 121, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_upload = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_upload.setObjectName("btn_upload")
        self.gridLayout.addWidget(self.btn_upload, 0, 0, 1, 1)
        self.cbo_algorithms = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbo_algorithms.setObjectName("cbo_algorithms")
        self.cbo_algorithms.addItem("")
        self.cbo_algorithms.addItem("")
        self.gridLayout.addWidget(self.cbo_algorithms, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.btn_transform = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_transform.setObjectName("btn_transform")
        self.gridLayout.addWidget(self.btn_transform, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_upload.setText(_translate("MainWindow", "Upload Image"))
        self.cbo_algorithms.setItemText(0, _translate("MainWindow", "High Pass Filtering"))
        self.cbo_algorithms.setItemText(1, _translate("MainWindow", "Low Pass Filtering"))
        self.label.setText(_translate("MainWindow", "Choose Algorithms"))
        self.btn_transform.setText(_translate("MainWindow", "Transform"))
